name: demo2020
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2103061

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: any

  azlistview: ^1.0.2
  provider: ^5.0.0
  nav_router: ^0.0.7
  flutter_sticky_header: ^0.5.0
  gzx_dropdown_menu: ^2.1.0
  auto_size_text: ^2.1.0
  flutter_luban: ^0.1.11
  path_provider: ^1.6.7
  flutter_swiper: ^1.1.6
  common_utils: ^1.2.4
  flutter_datetime_picker: ^1.5.0
  flutter_cupertino_data_picker: ^0.8.6
  fluttertoast: ^7.1.8
  synchronized: ^3.0.0
  shared_preferences: ^0.5.7
  webview_flutter: ^2.0.8
  jmessage_flutter: 0.6.5
  jpush_flutter: ^0.5.5
  dio: 3.0.9
  sqflite: ^1.1.0+1
  url_launcher: ^5.4.5
  keyboard_visibility: ^0.5.6
  flutter_easyrefresh: ^2.1.0
  pull_to_refresh: ^1.6.4
  flutter_staggered_grid_view: ^0.3.4
  city_pickers: ^0.1.17
  package_info: ^0.4.0+17
  awesome_dialog: ^1.3.1
#  sharesdk_plugin: ^1.2.4
  flutter_slidable: ^0.5.7
  flutter_spinkit: ^3.1.0
  flutter_amap_location_plugin: ^1.0.1
  ovprogresshud: any
  date_format: 1.0.9
  pin_code_fields: 2.3.0+3
  photo_view: 0.9.1
  flutter_rating_bar: 3.0.1+1
  awesome_button: 1.0.2
  image_picker: 0.6.7
  flutter_cupertino_settings: 0.4.0
  cached_network_image: 2.3.1
  permission: 0.1.7
  yin_drag_sacle: 0.0.2
  flutter_app_icon_badge: 2.0.0
  location_service_check:
    git:
      url: https://github.com/EchoPuda/location_service_check.git


dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - resources/role_json.json
    - resources/tone_skype.mp3
    - images/addImage.png
    - images/Logo.png
    - images/Launch.png
    - images/line_botm.jpg
    - images/jobing.png
    - images/nodata.png
    - images/Avatar/avatar.png
    - images/qrcode.png
    - images/tabbar/chat.png
    - images/tabbar/me.png
    - images/home/announcement.png
    - images/home/goldenEggs.png
    - images/home/increaseknowledge.png
    - images/home/job.png
    - images/home/shopping.png
    - images/home/timer.png
    - images/home/workers.png
    - images/home/city.png
    - images/home/hot.png
    - images/home/apply.png
    - images/home/wechatfriend.png
    - images/home/wechatCircle.png
    - images/password/unvisible.png
    - images/password/visible.png
    - images/member/apply.png
    - images/member/binding.png
    - images/member/collect.png
    - images/member/collection.png
    - images/member/dividend.png
    - images/member/eventHandling.png
    - images/member/feedback.png
    - images/member/gold.png
    - images/member/memberbg.png
    - images/member/disabled.png
    - images/member/partner.png
    - images/member/pushmoney.png
    - images/member/resume.png
    - images/member/seting.png
    - images/member/userinfo.png
    - images/member/seniorpartner.png
    - images/member/wage.png
    - images/member/wallet.png
    - images/member/wallet/icon-wallet-001.png
    - images/member/wallet/icon-wallet-002.png
    - images/member/wallet/icon-wallet-003.png
    - images/member/wallet/icon-wallet-004.png
    - images/member/wallet/icon-wallet-005.png
    - images/member/wallet/icon-wallet-006.png
    - images/member/wallet/icon-wallet-007.png
    - images/member/wallet/icon-wallet-008.png
    - images/member/wallet/icon-wallet-009.png
    - images/member/wallet/icon-wallet-010.png
    - images/member/wallet/icon-wallet-011.png
    - images/member/wallet/icon-wallet-012.png
    - images/member/wallet/icon-wallet-013.png
    - images/member/wallet/icon-wallet-014.png
    - images/member/wallet/icon-wallet-015.png
    - images/member/wallet/icon-wallet-016.png
    - images/member/wallet/icon-wallet-017.png

    - images/member/teacher.png
    - images/member/price.png
    - images/member/workflow.png
    - images/member/word.png
    - images/member/preferences.png
    - images/member/personal.png
    - images/member/wordtime.png
    - images/member/qrcode.png
    - images/member/loans.png
    - images/member/verify.png
    - images/member/history.png
    - images/member/check.png
    - images/member/factory.png
    - images/member/quit.png
    - images/member/clockin.png
    - images/member/leave.png
    - images/member/reimbursement.png
    - images/member/entry.png
    - images/member/payslip.png
    - images/member/qrcode/qrcode.png
    - images/member/qrcode/qrcodebg.png
    - images/member/qrcode/qrcodelogo.png
    - images/member/qrcode/qrcodeContentbg.png
    - images/member/event.png
    - images/member/overtime0.png
    - images/member/overtime1.png
    - images/member/overtime2.png
    - images/member/overtime3.png
    - images/loading.jpg
    - images/contact_list_normal.png
    - images/contact_list_pressed.png
    - images/find_normal.png
    - images/find_pressed.png
    - images/profile_normal.png
    - images/profile_pressed.png
    - images/weixin_normal.png
    - images/weixin_pressed.png
    - images/icon_menu_addfriend.png
    - images/icon_menu_group.png
    - images/icon_menu_scan.png
    - images/icon_addfriend.png
    - images/icon_groupchat.png
    - images/icon_public.png
    - images/icon_friends.png
    - images/icon_scan.png
    - images/icon_shake.png
    - images/icon_look.png
    - images/icon_search.png
    - images/icon_near.png
    - images/icon_bottle.png
    - images/icon_shop.png
    - images/icon_game.png
    - images/icon_link.png
    - images/icon_me_card.png
    - images/icon_me_collect.png
    - images/icon_me_money.png
    - images/icon_me_photo.png
    - images/icon_me_setting.png
    - images/icon_me_smile.png
    - images/code.png
    - images/tutu.png

    - assets/data/china.json